const express = require("express");
const BaseFareController = require("../controllers/basefare");
const router = express.Router();
router.post("/addfuel",BaseFareController.createFuel);
router.post("/addfare", BaseFareController.createfare);
router.post("/farelist", BaseFareController.getfare);
router.patch("/updatefare/:id", BaseFareController.updateFare);
router.delete("/deletefare/:_id", BaseFareController.deleteFare);
router.get("/allfare",BaseFareController.getAllfare);
module.exports = router;
